name: Publish
on:
  push:
jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v5
      - run: hugo
      - uses: actions/git-pages@v2
        with:
          site: https://steiger.codeberg.page/davidbeckonline-site/
          token: ${{ forge.token }}
          source: public/
